import numpy as np
from scipy.ndimage import gaussian_filter


def add_gaussian_noise(image, severity):
    # severity: std of noise, as a fraction of the image's own intensity range
    img_range = image.max() - image.min()
    noise = np.random.normal(0, severity * img_range, image.shape)
    return image + noise


def add_rician_noise(image, severity):
    # Rician noise is the physically correct noise model for MAGNITUDE MRI
    # images (unlike additive Gaussian, which is more appropriate for the
    # complex-valued raw k-space data) -- more clinically realistic than
    # plain Gaussian for this specific robustness test
    img_range = image.max() - image.min()
    sigma = severity * img_range
    noise_real = np.random.normal(0, sigma, image.shape)
    noise_imag = np.random.normal(0, sigma, image.shape)
    return np.sqrt((image + noise_real) ** 2 + noise_imag ** 2)


def add_bias_field(image, severity):
    # simulates MRI intensity inhomogeneity: a smooth, low-frequency
    # multiplicative field across the image, generated by heavily
    # smoothing random low-resolution noise
    H, W = image.shape[0], image.shape[1]
    low_res = np.random.normal(1.0, severity, (max(4, H // 20), max(4, W // 20)))
    field = np.array([
        np.interp(np.linspace(0, low_res.shape[0] - 1, H),
                   np.arange(low_res.shape[0]), low_res[:, j])
        for j in range(low_res.shape[1])
    ]).T
    field = np.array([
        np.interp(np.linspace(0, field.shape[1] - 1, W),
                   np.arange(field.shape[1]), field[i, :])
        for i in range(field.shape[0])
    ])
    field = gaussian_filter(field, sigma=min(H, W) / 10)
    if image.ndim == 3:
        field = field[:, :, None]
    return image * field


def add_motion_blur(image, severity):
    # severity controls blur kernel size (simulates patient motion during acquisition)
    sigma = severity * 5  # up to a few pixels of directional smoothing
    return gaussian_filter(image, sigma=(sigma, sigma * 0.3) + (0,) * (image.ndim - 2))